cms/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^songs/$', views.songs, name='songs'),
    url(r'^songs/approve/$', views.approve_song, name='approve_song'),
    url(r'^songs/download/(?P<file_type>.*)/$', views.download_songs, name='download_songs'),
    url(r'^songs/update/(?P<pk>\d+)/$', views.update_song, name='update_song'),
    url(r'^songs/delete/(?P<pk>\d+)/$', views.delete_song, name='delete_song'),

    url(r'^invitees/$', views.invitees, name='invitees'),
    url(r'^invitees/create/$', views.create_invitee, name='invitee_create'),
    url(r'^invitees/update/(?P<pk>\d+)/$', views.update_invitee, name='update_invitee'),
    url(r'^invitees/delete/(?P<pk>\d+)/$', views.delete_invitee, name='delete_invitee'),

    url(r'^emails/$', views.emails, name='emails'),
    url(r'^emails/create/$', views.create_email, name='create_email'),
    url(r'^emails/update/(?P<pk>\d+)/$', views.update_email, name='update_email'),
    url(r'^emails/delete/(?P<pk>\d+)/$', views.delete_email, name='delete_email'),
    url(r'^emails/preview/(?P<pk>\d+)/$', views.preview_email, name='preview_email'),

    url(r'^send-emails/$', views.send_emails, name='send_emails'),
    url(r'^migrations/$', views.migrations, name='migrations'),
    url(r'^migrations/invitees/$', views.migrate_invitees, name='migrate_invitees'),
]

# handler403 = views.cms_forbidden

wedding/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

import session_csrf
session_csrf.monkeypatch()

from public import views as public_views


urlpatterns = [
    url(r'^_ah/', include('djangae.urls')),
    url(r'^csp/', include('cspreports.urls')),
    url(r'^auth/', include('djangae.contrib.gauth.urls', namespace='login')),
    url(r'^cms/', include('cms.urls', namespace='cms')),
]

public_patterns = [
    url(r'^$', public_views.home, name='home'),
    url(r'^details/$', public_views.details, name='details'),
    url(r'^song-wishlist/$', public_views.song_wishlist, name='song_wishlist'),
    url(r'^song-wishlist-thanks/$', public_views.song_wishlist_thanks, name='song_wishlist_thanks'),
    url(r'^rsvp/$', public_views.rsvp, name='rsvp'),
    url(r'^rsvp-thanks/$', public_views.rsvp_thanks, name='rsvp_thanks'),
    url(r'^contact/$', public_views.contact, name='contact'),
    url(r'^change_language/(?P<lang_code>.*)/$', public_views.change_language, name='change_language'),
]

urlpatterns += i18n_patterns(
    url(r'', include(public_patterns, namespace='public')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cms/models.py
from django.db import models

# Create your models here.

cms/views.py
import csv
import logging
from datetime import datetime

from google.appengine.api import mail
from django.conf import settings
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    RedirectView,
    UpdateView,
    View,
    FormView,
    TemplateView)

from wedding import mixins
from wedding.forms import EmailForm, InviteeForm
from wedding.models import (
    Invitee,
    Song,
    get_email_class,
    get_email_content,
    RSVP_URL_TOKEN,
    INVITEE_NAME_TOKEN,
)
MIGRATIONS = (
    ('invitees', 'Re-save all invitee instances'),
)


class HomeView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy("cms:songs")

home = HomeView.as_view()


class SongsView(mixins.OrderByMixin, mixins.ViewNameMixin, ListView):
    page_name = 'songs'
    template_name = 'cms/songs.html'
    model = Song

songs = SongsView.as_view()


class DownloadSongsView(View):
    def get(self, request, *args, **kwargs):
        file_type = kwargs.get('file_type')
        response = HttpResponse(content_type='text/{}'.format(file_type))

        approved_songs = Song.objects.filter(is_approved=True).order_by('artist')
        date_now = str(datetime.now())

        if file_type == 'csv':
            file_name = 'approved-songs-{}.csv'.format(date_now)
            response['Content-Disposition'] = 'attachment; filename="{}"'.format(file_name)

            writer = csv.writer(response)
            writer.writerow(['Song title', 'Artist name', 'Submitted by'])

            for song in approved_songs:
                writer.writerow([
                    unicode(song.name).encode('utf-8'),
                    unicode(song.artist).encode('utf-8'),
                    unicode(song.submitted_by).encode('utf-8'),
                ])
        elif file_type == 'plain':
            file_name = 'approved-songs-{}.txt'.format(date_now)
            response['Content-Disposition'] = 'attachment; filename="{}"'.format(file_name)
            for song in approved_songs:
                line = '{}, {}\n'.format(song.name, song.artist)
                response.write(unicode(line).encode('utf-8'))

        return response

download_songs = DownloadSongsView.as_view()


class UpdateSongView(mixins.ViewNameMixin, UpdateView):
    page_name = 'songs'
    template_name = 'cms/song_form.html'
    model = Song
    success_url = reverse_lazy('cms:songs')

update_song = UpdateSongView.as_view()


class DeleteSongView(mixins.ViewNameMixin, DeleteView):
    page_name = 'songs'
    template_name = 'cms/song_delete_confirmation.html'
    model = Song
    success_url = reverse_lazy('cms:songs')

delete_song = DeleteSongView.as_view()


class ApproveSong(View):
    success_url = reverse_lazy('cms:songs')

    def post(self, request, *args, **kwargs):
        song_id = int(request.POST.get('song_id'))
        song_approved = request.POST.get('is_approved') == 'True'
        song = Song.objects.get(id=song_id)
        song.is_approved = song_approved
        song.save()
        return redirect(self.success_url)

    def get(self, request, *args, **kwargs):
        return redirect(self.success_url)

approve_song = ApproveSong.as_view()


class InviteesView(mixins.OrderByMixin, mixins.ViewNameMixin, ListView):
    model = Invitee
    page_name = 'invitees'
    template_name = 'cms/invitees.html'

    def get_context_data(self, **kwargs):
        ctx = super(InviteesView, self).get_context_data(**kwargs)
        Email = get_email_class()
        ctx['emails'] = Email.objects.all()
        return ctx

invitees = InviteesView.as_view()


class InviteeCreateView(mixins.ViewNameMixin, CreateView):
    form_class = InviteeForm
    model = Invitee
    page_name = 'invitees'
    success_url = reverse_lazy('cms:invitees')
    template_name = 'cms/invitee_form.html'

create_invitee = InviteeCreateView.as_view()


class InviteeUpdateView(mixins.ViewNameMixin, UpdateView):
    form_class = InviteeForm
    model = Invitee
    page_name = 'invitees'
    success_url = reverse_lazy('cms:invitees')
    template_name = 'cms/invitee_form.html'

update_invitee = InviteeUpdateView.as_view()


class InviteeDeleteView(mixins.ViewNameMixin, DeleteView):
    model = Invitee
    page_name = 'invitees'
    success_url = reverse_lazy('cms:invitees')
    template_name = 'cms/invitee_delete_confirmation.html'

delete_invitee = InviteeDeleteView.as_view()


class SendEmailsView(View):
    def post(self, *args, **kwargs):

        invitee_ids = self.request.POST.getlist('invitees[]')
        email_id = self.request.POST.get('email')

        Email = get_email_class()

        for invitee_id in invitee_ids:
            invitee = Invitee.objects.get(pk=invitee_id)

            # Check if the email has already been sent to the invitee.
            emails_sent_to_invitee_ids = invitee.get_email_ids()
            if email_id in emails_sent_to_invitee_ids:
                continue

            email = Email.objects.get(pk=email_id)

            message = mail.EmailMessage(
                sender="Javi Manzano <{}>".format(settings.EMAIL_FROM),
                subject="You're invited to our wedding"
            )

            message.to = u'{} <{}>'.format(
                unicode(invitee.fullname),
                invitee.email
            )

            message_html = get_email_content(email=email, language=invitee.language)

            # Replace tokens in the email for their values
            message_html = message_html.replace(INVITEE_NAME_TOKEN, invitee.fullname)
            rsvp_url = '{}{}?invitee={}'.format(settings.SERVER_DOMAIN, reverse('public:rsvp'), invitee.token)
            # Replace the language in the `rsvp_url` for nothing - this should be done in a nicer way.
            rsvp_url = rsvp_url.replace('/en/', '/')
            rsvp_url = rsvp_url.replace('/es/', '/')
            message_html = message_html.replace(RSVP_URL_TOKEN, rsvp_url)

            logging.info(message_html)

            message.html = message_html
            message.send()

            # Add email id to invitee emails list.
            if email_id not in emails_sent_to_invitee_ids:
                emails_sent_to_invitee_ids.append(email_id)
                invitee.emails = ','.join(emails_sent_to_invitee_ids)
                invitee.save()

        return HttpResponse('OK')

send_emails = SendEmailsView.as_view()


class EmailView(mixins.ViewNameMixin, ListView):
    model = None
    page_name = 'emails'
    template_name = 'cms/emails.html'

    def get_queryset(self):
        Email = get_email_class()
        return Email.objects.all()

emails = EmailView.as_view()


class EmailCreateView(mixins.ViewNameMixin, FormView):
    form_class = EmailForm
    page_name = 'emails'
    success_url = reverse_lazy('cms:emails')
    template_name = 'cms/email_form.html'

    def form_valid(self, form):
        form.save()
        return super(EmailCreateView, self).form_valid(form)

create_email = EmailCreateView.as_view()


class EmailUpdateView(mixins.ViewNameMixin, FormView):
    form_class = EmailForm
    page_name = 'emails'
    success_url = reverse_lazy('cms:emails')
    template_name = 'cms/email_form.html'

    def get(self, request, *args, **kwargs):
        Email = get_email_class()
        email_pk = self.kwargs.get('pk')
        self.object = Email.objects.get(pk=email_pk)
        return super(EmailUpdateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        Email = get_email_class()
        email_pk = self.kwargs.get('pk')
        self.object = Email.objects.get(pk=email_pk)
        return super(EmailUpdateView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return super(EmailUpdateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(EmailUpdateView, self).get_form_kwargs()
        if hasattr(self, 'object'):
            kwargs.update({'instance': self.object})
        return kwargs

update_email = EmailUpdateView.as_view()


class EmailDeleteView(mixins.ViewNameMixin, DeleteView):
    page_name = 'emails'
    success_url = reverse_lazy('cms:emails')
    template_name = 'cms/email_delete_confirmation.html'

    def get_object(self, queryset=None):
        Email = get_email_class()
        email_pk = self.kwargs.get('pk')
        return Email.objects.get(pk=email_pk)

delete_email = EmailDeleteView.as_view()


class EmailPreviewView(View):
    def get(self, *args, **kwargs):
        language = self.request.GET.get('language')
        Email = get_email_class()
        email_pk = kwargs.get('pk')
        email = Email.objects.get(pk=email_pk)
        return HttpResponse(get_email_content(email=email, language=language))

preview_email = EmailPreviewView.as_view()


class MigrationsView(mixins.ViewNameMixin, TemplateView):
    page_name = 'migrations'
    template_name = 'cms/migrations.html'

    def get_context_data(self, **kwargs):
        ctx = super(MigrationsView, self).get_context_data(**kwargs)
        ctx.update(migrations=MIGRATIONS)
        return ctx

migrations = MigrationsView.as_view()


class MigrateInviteesView(mixins.ViewNameMixin, TemplateView):
    page_name = 'migrate_invitees'
    template_name = 'cms/migrate_invitees.html'

    def dispatch(self, request, *args, **kwargs):
        # Re-save invitees.
        all_invitees = Invitee.objects.all()
        for invitee in all_invitees:
            invitee.save()
        return super(MigrateInviteesView, self).dispatch(request, *args, **kwargs)


migrate_invitees = MigrateInviteesView.as_view()

templates/cms/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.png' %}">

    <title>Magda and Javi CMS - {% block page_title %}{% endblock page_title %}</title>

    {% if debug %}
        <link rel="stylesheet" href="{% static 'libs/bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'libs/bootstrap/dist/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/cms.css' %}">
    {% else %}
        <link rel="stylesheet" href="{% static 'css/cms.min.css' %}">
    {% endif %}
</head>

<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'cms:home' %}">Magda and Javi CMS</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li {% ifequal page_name 'songs' %}class="active"{% endifequal %}><a href="{% url 'cms:songs' %}">Songs</a></li>
                    <li {% ifequal page_name 'invitees' %}class="active"{% endifequal %}><a href="{% url 'cms:invitees' %}">Invitees</a></li>
                    <li {% ifequal page_name 'emails' %}class="active"{% endifequal %}><a href="{% url 'cms:emails' %}">Emails</a></li>
                    <li {% ifequal page_name 'migrations' %}class="active"{% endifequal %}><a href="{% url 'cms:migrations' %}">Migrations</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="{% block container_class %}container-fluid{% endblock container_class %}">{% block content %}{% endblock content %}</div>

    {% if debug %}
        <script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    {% else %}
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endif %}
    {% block extra_js %}{% endblock extra_js %}
</body>
</html>

templates/cms/email_delete_confirmation.html
{% extends 'cms/base.html' %}
{% load static %}

{% block page_title %}
    Invitation emails
{% endblock page_title %}

{% block content %}

    <h1>Delete email {{ invitationemail }}</h1>

    <form action="" method="post">
        {% csrf_token %}

        <p>Are you sure you want to delete this email?</p>

        <a href="{% url 'cms:emails' %}" class="btn btn-default">Cancel</a>
        <input type="submit" value="Yes, delete it" class="btn btn-danger">
    </form>

{% endblock content %}

templates/cms/emails.html
{% extends 'cms/base.html' %}
{% load static form_tags %}

{% block page_title %}
    Email credentials
{% endblock page_title %}

{% block content %}

    <h1>Invitation emails</h1>

    <p class="text-right">
        <a class="btn btn-primary" href="{% url 'cms:create_email' %}">Create Invitation email</a>
    </p>

    <div class="table-wrp">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Email name</th>
                    <th>Preview</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for email in email_list %}
                <tr {% if song.is_approved %}class="success"{% endif %}>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ email.name }}</td>
                    <td class="email-preview"><iframe src="{% url 'cms:preview_email' email.pk %}?language=en" width="100%" height="300" frameborder="0"></iframe></td>
                    <td>
                        <p>
                            <a href="{% url 'cms:update_email' email.pk %}" class="btn btn-default btn-sm">Update</a>
                            <a href="{% url 'cms:delete_email' email.pk %}" class="btn btn-danger btn-sm">Delete</a>
                        </p>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td>0</td>
                    <td>No emails yet</td>
                    <td></td>
                    <td></td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>

{% endblock content %}

templates/cms/invitees.html
{% extends 'cms/base.html' %}
{% load static %}

{% block page_title %}
    RSVPs
{% endblock page_title %}

{% block content %}

    <h1>Invitees</h1>

    <div class="row margin-row">
        <div class="col-sm-6">
            {% for email in emails %}
            <form action="" data-csrftoken="{{ csrf_token }}">
                <button data-url="{% url 'cms:send_emails' %}" data-email-id="{{ email.pk }}" class="btn btn-default send-email">Send "{{ email }}"</button>
            </form>
            {% endfor %}
        </div>
        <div class="col-sm-6 text-right">
            <a class="btn btn-primary" href="{% url 'cms:invitee_create' %}">Create invitee</a>
            <a class="btn btn-default" href="#to-be-implemented">Download as Text file</a>
            <a class="btn btn-default" href="#to-be-implemented">Download as CSV</a>
        </div>
    </div>

    <div class="table-wrp">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>#</th>
                    <th>First name
                        <a href="{% url 'cms:invitees' %}?order_by=first_name"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-first_name"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Last name
                        <a href="{% url 'cms:invitees' %}?order_by=last_name"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-last_name"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Email
                        <a href="{% url 'cms:invitees' %}?order_by=email"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-email"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Inviter
                        <a href="{% url 'cms:invitees' %}?order_by=inviter"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-inviter"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Language
                        <a href="{% url 'cms:invitees' %}?order_by=language"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-language"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Emails sent
                        <a href="{% url 'cms:invitees' %}?order_by=emails"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-emails"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Invitation status
                        <a href="{% url 'cms:invitees' %}?order_by=invitation_status"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-invitation_status"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Has flight
                        <a href="{% url 'cms:invitees' %}?order_by=has_flight"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-has_flight"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Has +1
                        <a href="{% url 'cms:invitees' %}?order_by=has_plusone"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-has_plusone"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Token</th>
                    <th>Created
                        <a href="{% url 'cms:invitees' %}?order_by=added"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-added"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Updated
                        <a href="{% url 'cms:invitees' %}?order_by=updated"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:invitees' %}?order_by=-updated"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for invitee in invitee_list %}
                <tr data-row="{{ invitee.pk }}" class="invitee-row">
                    <td>
                        {{ forloop.counter }}
                        <input type="checkbox" class="invitee-selector" data-id="{{ invitee.pk }}" tabindex="1">
                    </td>
                    <td>{{ invitee.first_name }}</td>
                    <td>{{ invitee.last_name }}</td>
                    <td>{{ invitee.email }}</td>
                    <td>{{ invitee.get_inviter }}</td>
                    <td>{{ invitee.get_language }}</td>
                    <td>
                        {% for email in invitee.get_emails %}
                        <span class="invitation-sent--yes">{{ email }}</span>
                        {% empty %}
                        <span class="invitation-sent--no">No emails sent</span>
                        {% endfor %}
                    </td>
                    <td><span class="invitation-status--{{ invitee.invitation_status }}">{{ invitee.get_invitation_status }}</span></td>
                    <td>
                        <span class="has-flight--{{ invitee.has_flight|yesno:"yes,no,no" }}">
                            {{ invitee.has_flight|yesno:"Yes,No,Unknown" }}
                        </span>
                    </td>
                    <td>
                        <span class="has-plusone--{{ invitee.has_plusone|yesno:"yes,no,no" }}">
                            {{ invitee.has_plusone|yesno:"Yes,No,Unknown" }}
                        </span>
                    </td>
                    <td>{{ invitee.token }}</td>
                    <td>{{ invitee.added }}</td>
                    <td>{{ invitee.updated }}</td>
                    <td>
                        <a href="{% url 'cms:update_invitee' invitee.id %}" class="btn btn-default btn-sm">Update</a>
                        <a href="{% url 'cms:delete_invitee' invitee.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td>0</td>
                    <td>No invitees yet</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock content %}


{% block extra_js %}
    <script src="{% static 'js/invitees.js' %}"></script>
{% endblock extra_js %}

templates/cms/migrate_invitees.html
{% extends 'cms/base.html' %}
{% load static form_tags %}

{% block page_title %}
    Migrate invitees
{% endblock page_title %}

{% block content %}

    <h1>All the invitees have been resaved.</h1>

    <a href="{% url 'cms:migrations' %}">Go back to the migrations UI.</a>

{% endblock content %}

templates/cms/songs.html
{% extends 'cms/base.html' %}
{% load static %}

{% block page_title %}
    Songs
{% endblock page_title %}

{% block content %}

    <h1>Submitted songs</h1>

    <p class="text-right">
        <a class="btn btn-default" href="{% url 'cms:download_songs' 'plain' %}">Download as Text file</a>
        <a class="btn btn-default" href="{% url 'cms:download_songs' 'csv' %}">Download as CSV</a>
    </p>

    <div class="table-wrp">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Song title
                        <a href="{% url 'cms:songs' %}?order_by=name"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:songs' %}?order_by=-name"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Artist name
                        <a href="{% url 'cms:songs' %}?order_by=artist"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:songs' %}?order_by=-artist"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Submitted by
                        <a href="{% url 'cms:songs' %}?order_by=submitted_by"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:songs' %}?order_by=-submitted_by"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Added
                        <a href="{% url 'cms:songs' %}?order_by=added"><i class="glyphicon glyphicon-triangle-bottom"></i></a>
                        <a href="{% url 'cms:songs' %}?order_by=-added"><i class="glyphicon glyphicon-triangle-top"></i></a>
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for song in song_list %}
                <tr {% if song.is_approved %}class="success"{% endif %}>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ song.name }}</td>
                    <td>{{ song.artist }}</td>
                    <td>{{ song.submitted_by }}</td>
                    <td>{{ song.added }}</td>
                    <td>
                        <form action="{% url 'cms:approve_song' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="song_id" value="{{ song.id }}">
                            {% if song.is_approved %}
                                <input type="hidden" name="is_approved" value="False">
                                <input type="submit" value="Reject song" class="btn btn-default btn-sm">
                            {% else %}
                                <input type="hidden" name="is_approved" value="True">
                                <input type="submit" value="Approve song" class="btn btn-default btn-sm">
                            {% endif %}
                        </form>
                        <p>
                            <a href="{% url 'cms:update_song' song.id %}" class="btn btn-default btn-sm">Update</a>
                            <a href="{% url 'cms:delete_song' song.id %}" class="btn btn-danger btn-sm">Delete</a>
                        </p>
                        <p><a target="_blank" href="https://www.youtube.com/results?search_query={{ song.name }} {{ song.artist }}">Listen on youtube</a></p>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td>0</td>
                    <td>No songs yet</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock content %}